version: "3.9"
services:
  postgres-db:
    image: postgres:14.2-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: supertruyen

  consul:
    image: consul:1.15
    ports:
      - 8500:8500

  gateway:
    build:
      context: ./gateway
    ports:
      - 4000:4000

  migrate:
    build:
      context: ./migrate
      dockerfile: ./Dockerfile.dev
    environment:
      MIGRATE_DSN: ${MIGRATE_DSN}

  book-server:
    build:
      context: ./backend
      dockerfile: ./services/book_service/cmd/server/Dockerfile.dev
    environment:
      DB_DRIVER: postgres
      DB_DSN: ${DB_DSN}
      CLERK_TOKEN: ${CLERK_TOKEN}
      CONSUL_HOST: consul:8500
      GRPC_CONSUL_HOST: consul:8500

  chapter-server:
    build:
      context: ./backend
      dockerfile: ./services/chapter_service/cmd/server/Dockerfile.dev
    deploy:
      replicas: 3
    environment:
      DB_DRIVER: postgres
      DB_DSN: ${DB_DSN}
      CLERK_TOKEN: ${CLERK_TOKEN}
      CONSUL_HOST: consul:8500
