version: "3.9"
services:
  postgres-db:
    image: postgres:14.2-alpine
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
      POSTGRES_DB: supertruyen

  gateway:
    build:
      context: ./gateway
    ports:
      - 4000:4000

  book-server:
    build:
      context: ./backend
      dockerfile: ./services/book_service/server/Dockerfile.dev
    environment:
      DB_DRIVER: postgres
      DB_DSN: ${DB_DSN}
      CLERK_TOKEN: ${CLERK_TOKEN}

  chapter-server:
    build:
      context: ./backend
      dockerfile: ./services/chapter_service/server/Dockerfile.dev
    environment:
      DB_DRIVER: postgres
      DB_DSN: ${DB_DSN}
      CLERK_TOKEN: ${CLERK_TOKEN}
