version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  gateway:
    cmds:
      - docker-compose build gateway
      - docker-compose up gateway

  migrate:
    desc: migrate db
    cmds:
      - cd migrate && go run main.go {{.CLI_ARGS}}

  generate-proto:
    desc: generate proto files
    cmds:
      - cd backend/proto && buf generate

  book-server:
    cmds:
      - cd backend && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o book-server services/book_service/cmd/server/main.go
      - defer: cd backend && rm book-server
      - docker-compose build book-server
      - docker-compose up book-server

  chapter-server:
    cmds:
      - cd backend && GOOS=linux GARCH=amd64 CGO_ENABLED=0 go build -o chapter-server services/chapter_service/cmd/server/main.go
      - defer: cd backend && rm chapter-server
      - docker-compose build chapter-server
      - docker-compose up chapter-server
